from Products.ATVocabularyManager.config import TOOL_NAME as ATVOCABULARYTOOL
from Products.CMFCore.utils import getToolByName
def install(self):
    vocabs = {}
    vocabs['ryu'] = (
        ('~', 'unknown'),
        ('-', ' '),
        (',', 'multiple'),
        ('a', 'aikidô'),
        ('b', 'aikijutsu'),
        ('j', 'aikijô'),
        ('k', 'aikiken'),
        ('h', 'hojo kata'),
        ('j', 'Kashima Shinden Jikishinkage-ryû'),
        ('g', 'genkikai'),
        ('s', 'seitai'),
    )
    vocabs['keikoho'] = (
        ('~', 'unknown'),
        ('-', ' '),
        (',', 'multiple'),
        ('a', 'kakari keiko'),
        ('k', 'kigata'),
        ('t', 'tanren'),
        ('s', 'shinken'),
        ('k', 'kuzushi'),
        ('j', 'ushirowaza'),
        ('j', 'jiyû waza'),
        ('r', 'randori'),
        ('s', 'suburi'),
    )
    vocabs['?'] = (
        ('~', 'unknown'),
        ('-', ' '),
        (',', 'multiple'),
        ('s', 'suwari waza'),
        ('h', 'hanmi handachi waza'),
        ('t', 'tachi waza'),
        ('2', 'za'),
        ('3', 'seiza'),
        ('4', 'kiza'),
        ('5', 'wariza'),
        ('6', 'choza'),
        ('7', 'kaiza'),
        ('8', 'taiza'),
        ('9', 'gakuza'),
        ('0', 'anza'),
        ('j', 'hassô'),
        ('z', 'kahuza'),
    )
    vocabs['aite'] = (
        ('~', 'unknown'),
        ('-', ' '),
        (',', 'multiple'),
        ('1', '1'),
        ('2', '2'),
        ('3', '3'),
        ('4', '4'),
        ('5', '5'),
        ('6', '6'),
        ('7', '7'),
        ('8', '8'),
        ('t', 'taninzû tori'),
        ('k', 'kakari geiko'),
    )
    vocabs['buki'] = (
        ('~', 'unknown'),
        ('-', ' '),
        (',', 'multiple'),
        ('j', 'jô'),
        ('o', 'bô'),
        ('b', 'bokken, bokutô'),
        ('t', 'tantô'),
        ('w', 'wakizashi, shoto'),
        ('k', '(ken?,) katana'),
        ('a', 'tachi'),
        ('e', 'ken'),
        ('n', 'nihontô'),
        ('n', 'naginata'),
        ('y', 'yari'),
        ('s', 'tsuba'),
        ('s', 'saya'),
        ('u', 'bugukake'),
    )
    vocabs['kokukegi'] = (
        ('~', 'unknown'),
        ('-', ' '),
        (',', 'multiple'),
        ('a', 'kiawase shômen uchi'),
        ('b', 'katate dori ai hanmi'),
        ('c', 'katate dori gyaku hanmi'),
        ('d', 'ryôte dori'),
        ('e', 'shômen uchi'),
        ('f', 'katate ryôte dori'),
        ('g', 'kata dori'),
        ('h', 'ushiro ryôte dori'),
        ('i', 'yokomen uchi'),
        ('j', 'chûdan tsuki'),
        ('k', 'kata dori men uchi'),
        ('l', 'ushiro ryôkata dori'),
        ('m', 'jôdan tsuki'),
        ('n', 'ryôeri dori'),
        ('o', 'keri'),
        ('p', 'ushiro kubi jime'),
    )
    vocabs['uchi_soto'] = (
        ('~', 'unknown'),
        ('-', ' '),
        (',', 'multiple'),
        ('u', 'uchi sabaki'),
        ('s', 'soto sabaki'),
    )
    vocabs['taisabaki'] = (
        ('~', 'unknown'),
        ('-', ' '),
        (',', 'multiple'),
        ('a', 'mae ashi irimi'),
        ('b', 'ushiro ashi irimi'),
        ('c', 'mae ashi tenkan'),
        ('d', 'ushiro ashi tenkan'),
        ('e', 'mae ashi tenshin'),
        ('f', 'ushiro ashi tenshin'),
        ('g', 'mae ashi irimi tenkan'),
        ('h', 'ushiro ashi irimi tenkan'),
        ('i', 'mae ashi irimi tenkan tenshin'),
        ('j', 'ushiro ashi irimi tenkan tenshin'),
        ('k', 'mae ashi tenkan tenshin'),
        ('l', 'ushiro ashi tenkan tenshin'),
        ('m', 'ushiro ashi irimi tenkai'),
        ('n', 'ushiro ashi irimi ushiro ashi tenshin'),
    )
    vocabs['tesabaki'] = (
        ('~', 'unknown'),
        ('-', ' '),
        (',', 'multiple'),
        ('k', 'kami hanen'),
        ('s', 'shimo hanen'),
        ('t', 'tekubi gaeshi'),
        ('y', 'jyûji musubi'),
        ('u', 'uke nagashi'),
    )
    vocabs['note'] = (
        ('~', 'unknown'),
        ('-', ' '),
        (',', 'multiple'),
        ('u', 'uchinote'),
        ('k', 'katanote'),
    )
    vocabs['dan'] = (
        ('~', 'unknown'),
        ('-', ' '),
        (',', 'multiple'),
        ('g', 'gedan'),
        ('c', 'chûdan'),
        ('j', 'jôdan'),
        ('1', 'waki gamae'),
        ('2', 'gedan no kamae'),
        ('3', 'chûdan no kamae'),
        ('5', 'jôdan no kamae'),
    )
    vocabs['waza'] = (
        ('~', 'unknown'),
        ('-', ' '),
        (',', 'multiple'),
        ('a', 'ikkyô'),
        ('b', 'nikyô'),
        ('c', 'sankyô'),
        ('d', 'yonkyô'),
        ('e', 'sumiotoshi'),
        ('f', 'kotegaeshi'),
        ('g', 'iriminage'),
        ('h', 'shihônage'),
        ('i', 'gokyô'),
        ('j', 'hiji kime osae'),
        ('k', 'uchikaitensankyô'),
        ('l', 'ude garami'),
        ('m', 'aikigoshi'),
        ('n', 'aikiotoshi'),
        ('o', 'kaitennage'),
        ('p', 'ude kime nage'),
        ('q', 'maeotoshi'),
        ('r', 'hikiotoshi'),
        ('s', 'kiri otoshi'),
        ('t', 'kaitenotoshi'),
        ('u', 'ten chi nage'),
        ('v', 'genkeikokyûnage'),
        ('w', 'uchikaitennage'),
        ('x', 'furizuki kokyû nage'),
        ('y', 'jyûji garami'),
        ('z', 'tori fune kokyûnage'),
        ('0', 'shihô geri kokyûnage'),
        ('1', 'ude garami sankyô nage'),
        ('2', 'ude garami yonkyô nage'),
        ('3', 'koshi nage'),
        ('4', 'soto kaitennage'),
        ('5', 'zanto kokyû nage'),
        ('6', 'ude garami osae'),
        ('7', 'te guruma'),
        ('8', 'seoi guruma'),
        ('9', 'koshi guruma'),
        ('~', 'chin shin koshi guruma'),
    )
    vocabs['omote_ura'] = (
        ('~', 'unknown'),
        ('-', ' '),
        (',', 'multiple'),
        ('o', 'omote'),
        ('u', 'ura'),
    )
    vocabs['number'] = (
        ('~', 'unknown'),
        ('-', ' '),
        (',', 'multiple'),
        ('1', '1'),
        ('2', '2'),
        ('3', '3'),
        ('4', '4'),
        ('5', '5'),
        ('6', '6'),
        ('7', '7'),
        ('8', '8'),
        ('a', '1/8'),
        ('b', '2/8'),
        ('c', '3/8'),
        ('d', '4/8'),
        ('e', '5/8'),
        ('f', '6/8'),
        ('g', '7/8'),
        ('h', '8/8'),
        ('i', '1/4'),
        ('j', '2/4'),
        ('k', '3/4'),
        ('l', '4/4'),
    )
    vocabs['yin_yang'] = (
        ('~', 'unknown'),
        ('-', ' '),
        (',', 'multiple'),
        ('1', 'yin'),
        ('2', 'yang'),
    )
    vocabs['ri'] = (
        ('~', 'unknown'),
        ('-', ' '),
        (',', 'multiple'),
        ('1', 'su, mizu'),
        ('2', 'do, tsu'),
        ('3', 'hu'),
        ('4', 'ka, hi'),
        ('5', 'complete?'),
        ('h', 'haru'),
        ('n', 'natsu'),
        ('a', 'aki'),
        ('f', 'fuyu'),
        ('k', 'kôbô no genri'),
        ('u', 'uchi no ri'),
        ('o', 'osae no ri'),
        ('g', 'nage no ri'),
        ('z', 'zan no ri'),
    )
    vocabs['nage_osae'] = (
        ('~', 'unknown'),
        ('-', ' '),
        (',', 'multiple'),
        ('n', 'nage'),
        ('o', 'osae'),
        ('x', 'nage osae'),
    )
    vocabs['ukemi'] = (
        ('~', 'unknown'),
        ('-', ' '),
        (',', 'multiple'),
        ('1', 'boven onder ukemi'),
        ('2', 'mae ukemi'),
        ('3', 'ushiro ukemi'),
        ('4', 'yoko ukemi'),
        ('c', 'chokuto'),
        ('k', 'kaiten ukemi'),
        ('t', 'tobi ukemi'),
    )
    vocabs['?'] = (
        ('~', 'unknown'),
        ('-', ' '),
        (',', 'multiple'),
        ('1', 'Ueshiba, Morihei'),
        ('2', 'Ueshiba, Kisshomaru'),
        ('3', 'Moriteru Ueshiba'),
        ('t', 'Tada, Hiroshi'),
        ('i', 'Ikeda, Masatomi'),
        ('m', 'Francesco Marrella shidôin rokudan'),
        ('q', 'Michele Quaranta shidôin rokudan'),
        ('h', 'Fritz Heuscher shidôin rokudan'),
        ('u', 'Therese Uhr shidôin yondan'),
        ('g', 'Eric Graf fukoshidôin sandan'),
        ('s', 'Vincenzo Schiavone fukoshidôin sandan'),
        ('v', 'Sander van Geloven fukoshidôin nidan'),
    )
    vocabs['kazueru'] = (
        ('~', 'unknown'),
        ('-', ' '),
        (',', 'multiple'),
        ('0', 'zero'),
        ('1', 'ichi'),
        ('2', 'ni'),
        ('3', 'san'),
        ('4', 'shi, yon'),
        ('5', 'go'),
        ('6', 'roku'),
        ('7', 'shichi, nana'),
        ('8', 'hachi'),
        ('9', 'ku, kyû'),
        ('a', 'jû'),
        ('b', 'jû ichi'),
        ('c', 'ni jû'),
        ('d', 'ni jû ichi'),
        ('e', 'hyaku'),
        ('f', 'sen'),
        ('e', 'man'),
        ('h', 'ipponme'),
        ('i', 'nihonme'),
        ('j', 'sanbonme'),
        ('k', 'yonhonme'),
        ('l', 'gohonme'),
        ('m', 'rokuhonme'),
        ('n', 'nanahonme'),
        ('o', 'hachihonme'),
    )
    vocabs['dankai'] = (
        ('~', 'unknown'),
        ('-', ' '),
        (',', 'multiple'),
        ('n', 'dan'),
        ('k', 'kyû'),
        ('0', 'mukyû'),
        ('6', 'rokkyû'),
        ('5', 'gokyû'),
        ('4', 'yonkyû'),
        ('3', 'sankyû'),
        ('2', 'nikyû'),
        ('1', 'ikkyû'),
        ('y', 'yûdansha'),
        ('o', 'mudansha'),
        ('a', 'shodan'),
        ('b', 'nidan'),
        ('c', 'sandan'),
        ('d', 'yondan'),
        ('e', 'godan'),
        ('f', 'rokudan'),
        ('g', 'nanadan'),
        ('h', 'hachidan'),
        ('i', 'kudan'),
        ('j', 'jyûdan'),
    )
    vocabs['?'] = (
        ('~', 'unknown'),
        ('-', ' '),
        (',', 'multiple'),
        ('1', 'ai'),
        ('2', 'ki'),
        ('3', 'dô'),
        ('3', 'aikidô'),
        ('4', 'aikidôka'),
        ('5', 'aikikai'),
        ('8', 'uke'),
        ('9', 'tori'),
        ('n', 'nage'),
        ('u', 'uchidachi'),
        ('s', 'shidachi'),
    )
    vocabs['?'] = (
        ('~', 'unknown'),
        ('-', ' '),
        (',', 'multiple'),
        ('1', 'onegai shimasu'),
        ('2', 'doomo arigatoo gozaimashita'),
        ('3', 'hai'),
        ('4', '(hai) doozo'),
        ('5', 'yame'),
        ('6', 'hajime'),
        ('6', 'matte'),
        ('8', 'tate'),
        ('9', 'suwatte'),
        ('a', 'mawatte'),
        ('b', 'kotai'),
        ('c', 'morikai'),
        ('d', 'hantai'),
        ('e', 'aite kaite'),
        ('f', 'rei'),
        ('g', 'ritsurei'),
        ('h', 'zarei'),
    )
    vocabs['?'] = (
        ('~', 'unknown'),
        ('-', ' '),
        (',', 'multiple'),
        ('s', 'ôsensei'),
        ('o', 'sensei'),
        ('d', 'dôshu'),
        ('7', 'shihan'),
        ('8', 'shidoin'),
        ('9', 'fukushidoin'),
        ('a', 'senpai'),
        ('b', 'kôhai'),
        ('c', 'mudansha'),
        ('d', 'yûdansha'),
        ('e', 'dôjôcho'),
        ('f', 'deshi'),
        ('g', 'uchideshi'),
        ('h', 'sotodeshi'),
    )
    vocabs['?'] = (
        ('~', 'unknown'),
        ('-', ' '),
        (',', 'multiple'),
        ('0', 'dôjô'),
        ('1', 'kamiza'),
        ('2', 'shomiza'),
        ('3', 'joseki'),
        ('4', 'shimoseki'),
        ('5', 'tatami'),
        ('6', 'hombu'),
    )
    vocabs['ifuku'] = (
        ('~', 'unknown'),
        ('-', ' '),
        (',', 'multiple'),
        ('1', 'keikogi'),
        ('2', 'obi'),
        ('3', 'shiroobi'),
        ('4', 'kuroobi'),
        ('5', 'tabi'),
        ('6', 'zori'),
        ('7', 'hakama'),
    )
    vocabs['kakobogaku'] = (
        ('~', 'unknown'),
        ('-', ' '),
        (',', 'multiple'),
        ('a', 'hara'),
        ('b', 'tai'),
        ('c', 'shômen'),
        ('d', 'yokomen'),
        ('e', 'hiza'),
        ('f', 'kubi'),
        ('g', 'mune'),
        ('e', 'kata'),
        ('h', 'hiji'),
        ('i', 'ude'),
        ('j', 'tekubi'),
        ('k', 'te'),
        ('k', 'tegatana'),
        ('l', 'ashi'),
        ('m', 'asho kubi'),
        ('n', 'koshi'),
        ('o', 'eri'),
        ('p', 'mi'),
        ('s', 'sode'),
    )
    vocabs['?'] = (
        ('~', 'unknown'),
        ('-', ' '),
        (',', 'multiple'),
        ('a', 'ainuke'),
        ('b', 'aiuchi'),
        ('c', 'atemi'),
        ('d', 'budo'),
        ('e', 'kumijô'),
        ('f', 'kumitachi'),
        ('g', 'tachidori'),
        ('h', 'tantodori'),
        ('i', 'seigan'),
        ('j', 'kamae'),
        ('m', 'maai'),
        ('s', 'shikkou'),
        ('t', 'taiko'),
    )
    vocabs['?'] = (
        ('~', 'unknown'),
        ('-', ' '),
        (',', 'multiple'),
        ('h', 'hidari'),
        ('m', 'migi'),
        ('i', 'irimi'),
        ('k', 'kaiten'),
        ('1', 'mae'),
        ('2', 'ushiro'),
        ('3', 'yoko'),
        ('a', 'uchi'),
        ('b', 'soto'),
        ('n', 'naname'),
        ('c', 'chokuritsu'),
        ('s', 'suihei'),
        ('t', 'tate'),
        ('x', 'hantai'),
        ('8', 'happô'),
    )
    vocabs['undo'] = (
        ('~', 'unknown'),
        ('-', ' '),
        (',', 'multiple'),
        ('1', 'ikkyo undo'),
        ('2', 'tai no henkou'),
    )
    vocabs['hojonokata'] = (
        ('~', 'unknown'),
        ('-', ' '),
        (',', 'multiple'),
        ('1', 'haru no tachi'),
        ('2', 'natsu no tachi'),
        ('3', 'aki no tachi'),
        ('4', 'fuyu no tachi'),
        ('5', 'hassô happa'),
        ('6', 'itto ryôdan'),
        ('7', 'uten saten'),
        ('8', 'chotan ichimi'),
        ('9', 'ukeru'),
        ('a', 'taiken'),
        ('b', 'mokurei'),
        ('c', 'bakken'),
        ('d', 'ai seigan'),
        ('e', 'sokushin'),
        ('g', 'niô dachi'),
        ('h', 'kazashi'),
        ('i', 'ai jôdan'),
        ('j', 'tsume'),
        ('k', 'uchi komi'),
        ('l', 'morôde'),
        ('m', 'oshi komi'),
        ('n', 'ichimonji'),
        ('o', 'so tai'),
        ('p', 'tai atari'),
        ('q', 'hi tachi'),
        ('r', 'kasumi'),
        ('s', 'hitoemi'),
        ('t', 'muki'),
        ('u', 'kiri'),
        ('v', 'tome'),
        ('w', 'ura uchi'),
        ('x', 'shokô'),
        ('y', 'dai'),
        ('z', 'noken'),
    )
    vocabs['genkikai'] = (
        ('~', 'unknown'),
        ('-', ' '),
        (',', 'multiple'),
        ('~', 'dai en kokyû hô'),
        ('0', 'suu no kokyû'),
        ('1', 'yo no te kokyû'),
        ('2', 'in no te kokyû'),
        ('3', 'kimusubi no te kokyû'),
        ('4', 'aun no kokyû'),
        ('5', 'gen no kokyû'),
        ('6', 'ne undô'),
        ('a', 'yô dôhô'),
        ('b', 'môkan undô'),
        ('c', 'gasshô gasseki undô'),
        ('d', 'kingyo undô'),
        ('u', 'uma undô'),
    )
    vocabs['lists'] = (
        ('0', 'ryû'),
        ('1', 'keiko hô'),
        ('2', '?'),
        ('3', 'aite'),
        ('4', 'buki'),
        ('5', 'kokukegi'),
        ('6', 'uchi/soto'),
        ('7', 'tai sabaki'),
        ('8', 'te sabaki'),
        ('9', 'note'),
        ('a', 'dan'),
        ('b', 'waza'),
        ('c', 'omote/ura'),
        ('d', 'number'),
        ('f', 'yin/yang'),
        ('g', 'ri'),
        ('h', 'nage/osae'),
        ('i', 'ukemi'),
        ('j', '?'),
        ('k', 'kazueru'),
        ('l', 'dankai'),
        ('m', '?'),
        ('n', '?'),
        ('o', '?'),
        ('p', '?'),
        ('q', 'ifuku'),
        ('r', 'kakobôgaku'),
        ('s', '?'),
        ('t', '?'),
        ('u', 'undô'),
        ('v', 'hôjô no kata'),
        ('w', 'genkikai'),
    )
    portal=getToolByName(self,'portal_url').getPortalObject()
    atvm = getToolByName(portal, ATVOCABULARYTOOL)
    for vkey in vocabs.keys():
        vocabname = vkey
        if not hasattr(atvm, vocabname):
            atvm.invokeFactory('SimpleVocabulary', vocabname)
        vocab = atvm[vocabname]
        if len(vocab.getFolderContents()) < 2:
            for (ikey, value) in vocabs [vkey]:
                if not hasattr(vocab, ikey):
                    vocab.invokeFactory('SimpleVocabularyTerm', ikey)
                    vocab[ikey].setTitle(value)